INSERT INTO PLAYER (EMAILADDRESS, BIRTHDAY, FIRSTNAME, LASTNAME, PASSWORD, HEIGHT, NUMBER, POSITION, TEAM, WEIGHT) VALUES ('coelhomarcelo11@gmail.com', '1976-03-14', 'Marcelo', 'Coelho', '12345678', 100, 88, "forward", "LA", 92);
INSERT INTO PLAYER (EMAILADDRESS, BIRTHDAY, FIRSTNAME, LASTNAME, PASSWORD, HEIGHT, NUMBER, POSITION, TEAM, WEIGHT) VALUES ('coelhomarcelo22@gmail.com', '1976-03-14', 'Marcelo', 'Coelho', '1234abCD', 200, 88, "forward", "LA", 92);

--INSERT INTO PLAYER (EMAILADDRESS, BIRTHDAY, FIRSTNAME, LASTNAME) VALUES ('coelhomarcelo2@gmail.com', '1976-03-14', 'Marcelo', 'Coelho');
--INSERT INTO PLAYER (EMAILADDRESS, BIRTHDAY, FIRSTNAME, LASTNAME) VALUES ('coelhomarcelo3@gmail.com', '1976-03-14', 'Marcelo', 'Coelho');
--INSERT INTO PLAYER (EMAILADDRESS, BIRTHDAY, FIRSTNAME, LASTNAME, PASSWORD, ROLES ) VALUES ('me11@yahoo.com', '1998-09-21', 'Known', 'Anyone', '12345678', 'ADMIN' );
--INSERT INTO PLAYER (EMAILADDRESS, BIRTHDAY, FIRSTNAME, LASTNAME, PASSWORD, LIST ROLES ) VALUES ('kk11@gmail.com', '1978/05/23', 'Marcelo', 'KK', '12345678', 'USER' );